[package]
name = "musa"
version = "0.1.0"
edition = "2021"
rust-version = "1.87"

[dependencies]
crossterm = { version = "=0.29.0", default-features = false, features = ["events"] }
lofty = { version = "=0.24.0", default-features = false }
unicode-width = { version = "=0.2.2", default-features = false }
rodio = { version = "=0.22.2", default-features = false, features = [
    "playback",
    "flac",
    "mp3",
    "vorbis",
    "wav",
    "mp4",
] }

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
