[package]
name = "musa"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
walkdir = "2.5"
rodio = "0.17"
eframe = { version = "0.27", features = ["wgpu"] }
egui = "0.27"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "gif", "bmp", "tiff", "webp"] }
regex = "1.10"
